<?php

namespace Shirahcan\CalendarClient;

/**
 * Short names for zones whose English ICU name is only an offset ("GMT+1"): GENERATED from
 * calendar-ui's src/zoneAbbreviations.ts so screens and emails name a zone the same way (owner
 * 2026-10-09: "3:00 PM WAT"). [standard, daylight]. Do not edit by hand: change the TS table and
 * regenerate.
 */
final class ZoneAbbreviations
{
    /** @var array<string, array{0: string, 1?: string}> */
    public const TABLE = [
        'Africa/Lagos' => ['WAT'],
        'Africa/Kinshasa' => ['WAT'],
        'Africa/Douala' => ['WAT'],
        'Africa/Luanda' => ['WAT'],
        'Africa/Porto-Novo' => ['WAT'],
        'Africa/Niamey' => ['WAT'],
        'Africa/Ndjamena' => ['WAT'],
        'Africa/Libreville' => ['WAT'],
        'Africa/Nairobi' => ['EAT'],
        'Africa/Addis_Ababa' => ['EAT'],
        'Africa/Kampala' => ['EAT'],
        'Africa/Dar_es_Salaam' => ['EAT'],
        'Africa/Mogadishu' => ['EAT'],
        'Africa/Asmara' => ['EAT'],
        'Africa/Djibouti' => ['EAT'],
        'Africa/Harare' => ['CAT'],
        'Africa/Lusaka' => ['CAT'],
        'Africa/Maputo' => ['CAT'],
        'Africa/Kigali' => ['CAT'],
        'Africa/Blantyre' => ['CAT'],
        'Africa/Gaborone' => ['CAT'],
        'Africa/Lubumbashi' => ['CAT'],
        'Africa/Khartoum' => ['CAT'],
        'Africa/Johannesburg' => ['SAST'],
        'Africa/Maseru' => ['SAST'],
        'Africa/Mbabane' => ['SAST'],
        'Africa/Cairo' => ['EET', 'EEST'],
        'Africa/Tripoli' => ['EET'],
        'Africa/Casablanca' => ['WET', 'WEST'],
        'Africa/Algiers' => ['CET'],
        'Africa/Tunis' => ['CET'],
        'Asia/Kolkata' => ['IST'],
        'Asia/Calcutta' => ['IST'],
        'Asia/Karachi' => ['PKT'],
        'Asia/Dhaka' => ['BST'],
        'Asia/Kathmandu' => ['NPT'],
        'Asia/Colombo' => ['IST'],
        'Asia/Manila' => ['PHT'],
        'Asia/Shanghai' => ['CST'],
        'Asia/Hong_Kong' => ['HKT'],
        'Asia/Taipei' => ['CST'],
        'Asia/Singapore' => ['SGT'],
        'Asia/Kuala_Lumpur' => ['MYT'],
        'Asia/Jakarta' => ['WIB'],
        'Asia/Bangkok' => ['ICT'],
        'Asia/Ho_Chi_Minh' => ['ICT'],
        'Asia/Saigon' => ['ICT'],
        'Asia/Tokyo' => ['JST'],
        'Asia/Seoul' => ['KST'],
        'Asia/Dubai' => ['GST'],
        'Asia/Muscat' => ['GST'],
        'Asia/Riyadh' => ['AST'],
        'Asia/Qatar' => ['AST'],
        'Asia/Kuwait' => ['AST'],
        'Asia/Bahrain' => ['AST'],
        'Asia/Baghdad' => ['AST'],
        'Asia/Tehran' => ['IRST'],
        'Asia/Kabul' => ['AFT'],
        'Asia/Tashkent' => ['UZT'],
        'Asia/Almaty' => ['ALMT'],
        'Asia/Jerusalem' => ['IST', 'IDT'],
        'Asia/Beirut' => ['EET', 'EEST'],
        'Asia/Amman' => ['AST'],
        'Asia/Damascus' => ['AST'],
        'Asia/Yerevan' => ['AMT'],
        'Asia/Tbilisi' => ['GET'],
        'Asia/Baku' => ['AZT'],
        'Asia/Yangon' => ['MMT'],
        'Europe/London' => ['GMT', 'BST'],
        'Europe/Dublin' => ['GMT', 'IST'],
        'Europe/Lisbon' => ['WET', 'WEST'],
        'Europe/Paris' => ['CET', 'CEST'],
        'Europe/Berlin' => ['CET', 'CEST'],
        'Europe/Madrid' => ['CET', 'CEST'],
        'Europe/Rome' => ['CET', 'CEST'],
        'Europe/Amsterdam' => ['CET', 'CEST'],
        'Europe/Brussels' => ['CET', 'CEST'],
        'Europe/Vienna' => ['CET', 'CEST'],
        'Europe/Zurich' => ['CET', 'CEST'],
        'Europe/Stockholm' => ['CET', 'CEST'],
        'Europe/Oslo' => ['CET', 'CEST'],
        'Europe/Copenhagen' => ['CET', 'CEST'],
        'Europe/Warsaw' => ['CET', 'CEST'],
        'Europe/Prague' => ['CET', 'CEST'],
        'Europe/Budapest' => ['CET', 'CEST'],
        'Europe/Belgrade' => ['CET', 'CEST'],
        'Europe/Athens' => ['EET', 'EEST'],
        'Europe/Bucharest' => ['EET', 'EEST'],
        'Europe/Helsinki' => ['EET', 'EEST'],
        'Europe/Kiev' => ['EET', 'EEST'],
        'Europe/Kyiv' => ['EET', 'EEST'],
        'Europe/Sofia' => ['EET', 'EEST'],
        'Europe/Istanbul' => ['TRT'],
        'Europe/Moscow' => ['MSK'],
        'America/Sao_Paulo' => ['BRT'],
        'America/Bogota' => ['COT'],
        'America/Lima' => ['PET'],
        'America/Caracas' => ['VET'],
        'America/Argentina/Buenos_Aires' => ['ART'],
        'America/Buenos_Aires' => ['ART'],
        'America/Santiago' => ['CLT', 'CLST'],
        'America/La_Paz' => ['BOT'],
        'America/Guayaquil' => ['ECT'],
        'America/Montevideo' => ['UYT'],
        'America/Asuncion' => ['PYT', 'PYST'],
        'Australia/Sydney' => ['AEST', 'AEDT'],
        'Australia/Melbourne' => ['AEST', 'AEDT'],
        'Australia/Hobart' => ['AEST', 'AEDT'],
        'Australia/Brisbane' => ['AEST'],
        'Australia/Adelaide' => ['ACST', 'ACDT'],
        'Australia/Darwin' => ['ACST'],
        'Australia/Perth' => ['AWST'],
        'Pacific/Auckland' => ['NZST', 'NZDT'],
        'Pacific/Fiji' => ['FJT'],
        'Pacific/Kiritimati' => ['LINT'],
    ];
}
